config/routes.rb
Rails.application.routes.draw do

  root 'films#index'
  post '/', to: 'films#index'

   #navigations for static pages
   get 'about', to: 'films#about'
   get 'contact', to: 'films#contactUs'
   get 'admin_index', to: 'admins#index'

   #search routes
   post '/search', to: 'latests#search'
   get '/search', to: 'latests#index'
 
  #navigation for paginated music page
  post '/musics_index', to: 'musics#index'
  get '/musics_index', to: 'musics#index'
  
  
  #navigation for paginated video page
  post '/videos_index', to: 'videos#index'
  get '/videos_index', to: 'videos#index'

  #navigation for paginated news page
  post '/news_index', to: 'news#index'
  get '/news_index', to: 'news#index'

 

  #routes for downloads
  post '/video_download', to: 'videos#download'
  post '/music_download', to: 'musics#download'

  #routes for authentication
  post '/auth', to: 'artists#auth'
  
  resources :musics, :videos, :news, :artists

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
    has_many :musics
    has_many :videos
    has_many :news

    validates :name, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :musics

    validates :name, length: { minimum: 2 }
    validates :sex, inclusion: { in: %w(male female), message: "%{value} is not a valid sex" }
    validates :biography, length: { maximum: 500,  message: "%{count} characters is the maximum allowed" }
    validates :sex, presence: true
    validates :name, :email, :phone_number, uniqueness: true, presence: true
end

app/models/latest.rb
class Latest < ApplicationRecord
end

app/models/music.rb
class Music < ApplicationRecord
    belongs_to :artist, optional: true
    belongs_to :admin, optional: true
end

app/models/news.rb
class News < ApplicationRecord
    belongs_to :admin, optional: true

    attr_accessor :body

    def read_file(file_path)
        self.body = File.open("#{Rails.root}/public/#{file_path}", 'r'){ |f| f.read }
    end
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :admin, optional: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	def new
	end

	def index
	end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController
	#controller specific configuration

	def index
		# code for pagination to be removed for mobile
		#if(tot_content % @per_page== 0)
		#	@tot_nav_links = tot_content / @per_page
		#else
		#	@tot_nav_links = (tot_content / @per_page)+1
		#end

		respond_to do |format|
			format.json do 
				@query_offset = params[:offset].to_i
				@contents = Latest.select(:media_id, :media_type, :media_poster, :artist_name, :title).order(created_at: :desc).limit(6).offset(@query_offset)
				@query_offset += @contents.length
				@contents_json = Hash.new
				@contents_json["query"] = @query_offset
				@contents_json["contents"] = @contents.as_json
				render json: @contents_json
			end
			format.html do
				@query_offset=0;
				@contents = Latest.select(:media_id, :media_type, :media_poster, :artist_name, :title).order(created_at: :desc).limit(6)
				@query_offset += @contents.length
			end
		end			
	end

	def about
	end

	def contactUs
	end

end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
	def index
		respond_to do |format|
			format.json do 
				@query_offset = params[:offset].to_i
				@contents = Music.select(:media_id, :poster_path, :artist_name, :title).order(created_at: :desc).limit(1).offset(@query_offset)
				@query_offset += @contents.length
				@contents_json = Hash.new
				@contents_json["query"] = @query_offset
				@contents_json["contents"] = @contents.as_json
				render json: @contents_json
			end
			format.html do
				@query_offset=0;
				@contents = Music.select(:id, :poster_path, :artist_name, :title).order(created_at: :desc).limit(6)
				@query_offset += @contents.length
			end
		end
	end
	
	def new
		@music = Music.new
	end

	def create
		@musicService = MusicService.new(params)

		@musicService.create_locally()

		@music = @musicService.store_music()
		
		if @music
			flash[:customed_message] = @music.errors.full_messages
		end

		redirect_to admin_index_path
	end

	def show
		id = params[:id]
		@music = Music.find(id)
		@media = "musics/#{id}"
	end

	def download
		music_id = params[:music][:music_id]

		music =  Music.find(music_id)

		if music.valid?
			music_rel_path = music.music_path

			music_file = gen_absolute_file_path music_rel_path

			send_file(music_file)

			download_count = music.download_count + 1

			music.update(download_count: download_count)
		end
	end

	private
		def permit_music
			params.require(:music).permit(:producer, :music_path, :title, :poster_path, :album_title, :artist_name);
		end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
    def index
        respond_to do |format|
			format.json do 
				@query_offset = params[:offset].to_i
				@contents = News.select(:id, :image_path, :title).order(created_at: :desc).limit(6).offset(@query_offset)
				@query_offset += @contents.length
				@contents_json = Hash.new
				@contents_json["query"] = @query_offset
				@contents_json["contents"] = @contents.as_json
				render json: @contents_json
			end
			format.html do
				@query_offset=0
				@contents = News.select(:id, :image_path, :title).order(created_at: :desc).limit(6)
				@query_offset += @contents.length
			end
		end
    end

    def new
        @news = News.new
    end

    def create
        @newsService = NewsService.new(params)
		@newsService.create_locally

		@news = @newsService.store_news
		
		if @news
			flash[:customed_message] = @news.errors.full_messages
		end
        
        if @news
            flash[:customed_message] = @news.errors.full_messages
        end
        redirect_to admin_index_path
    end

    def show
        @news = News.find(params[:id])
        url = @news.news_file_url
        @news.read_file(url)
    end

    private
        def permit_news
            params.require(:news).permit( :title, :body, :released )
        end

        def write_file file, path
            file_name = file.original_filename

            file_ext = File.extname file_name

            news_file = File.new(path, "wb")

            news_file.write(file.read)

            news_file.close
        end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def format_name(name)
        name.split(' ').join('_')
    end

    def gen_relative_file_path(folder, folder_type, file_name)
        "/secure/#{folder_type}/#{folder}/#{file_name}"
    end

    def gen_absolute_file_path(path)
        "#{Rails.root}/public#{path}"
    end

    def gen_absolute_folder_path(type, folder)
        "#{Rails.root}/public/secure/#{type}/#{folder}"
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
    
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
	def write_file file, path
			file_name = file.original_filename

			file_ext = File.extname file_name

			new_file = File.new(path, "wb")

			new_file.write(file.read)

			new_file.close
		end
end

app/views/admins/index.html.erb
<% content_for :header do %>
  
<% end %>

<!-- MUSIC SECTION -->
<h1>MUSIC</h1>
<%= form_for :music, url: musics_path  do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :artist_name %><br>
    <%= form.text_field :artist_name %>
  </p>

  <p>
    <%= form.label :album_title %><br>
    <%= form.text_field :album_title %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.label :genre %><br>
    <%= select_tag "genres", options_for_select(["jazz","rock","blues","R & B", "Afro pop", "country", "Ragea", "trap", "shakuku", "highlife"], "jazz"), multiple: true, include_blank: true %>
  </p>

  <p>
    <%= form.label :composer %><br>
    <%= form.text_field :composer %>
  </p>

  <p>
    <%= form.label :producer %><br>
    <%= form.text_field :producer %>
  </p>

  <p>
    <%= form.label :released %><br>
    <%= form.date_field :released %>
  </p>

  <p>
    <%= form.label :music_poster %><br>
    <%= form.file_field :poster_file %>
  </p>

  <p>
    <%= form.label :path %><br>
    <%= form.file_field :music_file %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<!-- VIDEO SECTION -->
<h1>VIDEO</h1>
<%= form_for :video, url: videos_path  do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :producer %><br>
    <%= form.text_field :producer %>
  </p>

  <p>
    <%= form.label :released %><br>
    <%= form.date_field :released %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_field :description %>
  </p>

  <p>
    <%= form.label :video_poster %><br>
    <%= form.file_field :poster_file %>
  </p>

  <p>
    <%= form.label :path %><br>
    <%= form.file_field :video_file %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<!-- NEWS SECTION -->
<h1>NEWS</h1>
<%= form_for :news, url: '/news'  do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>

  <p>
    <%= form.label :released %><br>
    <%= form.date_field :released %>
  </p>

  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>

  <p>
    <%= form.label :news_image %><br>
    <%= form.file_field :image_path %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

<!-- Message -->

<% if flash[:customed_message] %>
      <%= content_tag :p, flash[:customed_message] %>
<% end -%>

app/views/layouts/_footer.html.erb
<footer>
    <hr/>
    <span id="copyright">copyright bjcityjamz.com</span>
</footer>

app/views/layouts/_header.html.erb
<header class="filmz-dark-bg">		
	<!-- DIV FOR SOCIAL MEDIA ICONS
	<div class="d-flex col-12 justify-content-center col-sm-12 col-md-12 col-lg-12 col-xl-12 filmz-follow filmz-follow filmz-wt-col ">
		<a href="#" data-toggle="tooltip" data-placement="auto" data-animate="true" title="" data-original-title="facebook"><i class="fab fa-facebook-square"></i></a>
		<a href="#" data-toggle="tooltip" data-placement="auto" data-animate="true" title="" data-original-title="twitter"><i class="fab fa-twitter-square"></i></a>
		<a href="#" data-toggle="tooltip" data-placement="auto" data-animate="true" title="" data-original-title="whatsapp"><i class="fab fa-whatsapp-square"></i></a>
		<a href="#" data-toggle="tooltip" data-placement="auto" data-animate="true" title="" data-original-title="flickr"><i class="fab fa-flickr"></i></a>
		<a href="#" data-toggle="tooltip" data-placement="auto" data-animate="true" title="" data-original-title="google plus"><i class="fab fa-google-plus"></i></a>
		<a id="signin" class="" href="">signin</a>
	</div> -->

	<!-- NAVIGATIONS -->
	<nav id="topNav">
		<div id="topNavSec">
			<a href="/">
				<%= image_tag("filmz2.png", id: "filmz-icon_small", alt: "filmz")%>
			</a>
			<ul id="myTopnav">
				<li id="resMenu" class="icon"><a href="javascript:void(0);">&#9776;</a></li>
			</ul>
		</div>
		<div id="navHolder" class="topnav">
			<ul class="topnav">
				<li><a href="/">HOME</a></li><hr class="navrul"/>
				<li><a href="/musics">MUSIC</a></li><hr class="navrul"/>
				<li><a href="/videos">VIDEOS</a></li><hr class="navrul"/>
				<li><a href="/news">NEWS</a></li>
			<ul>
		</div>
	</nav>

	<!-- DIV FOR SEARCH BOX -->
	
	<div class=" filmz-search col-12 col-lg-3 col-xl-2 filmz-search">
		<%= form_for :search, url: '/search', html:{ id: 'search-form', method: 'post'} do |form| %>
			<%= form.text_field :query, id: 'search-field-sm', placeholder: "Start searching", class: "search-field" %>
			<i class="search-btn fa fa-search" id="submit-icon" title="search"></i>
		<%end%>
	</div>
	<!--
	<section id="search-result">
		<p>HELLO WORLD HOW ARE THINGS GOING</p>
	<section>
	-->
</header>

app/views/layouts/_social_media_share.html.erb
<% content_for :social_media_meta do %>
    <meta property="og:url" content= '<%= "https://filmlegendary.herokuapp.com/#{@media}"%>' />
    <meta property="og:type" content= "website" />
    <meta property="og:title" content= "Film Legendary" />
    <meta property="og:description" content= "Get your best intertainment here" />
    <meta property="og:image" content= "https://image.shutterstock.com/image-vector/music-note-design-element-doodle-450w-616470641.jpg" />
<% end %>

<div id="share_holder">
    <!-- twitter -->
    <a class ="twitter-share-button temp_show" href="https://twitter.com/share?ref_src=twsrc%5Etfw" data-url='<%= "https://filmlegendary.herokuapp.com/#{@media}"%>' data-size="small" data-show-count="false"></a>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

    <!-- facebook -->
    <div id="fb-root"></div>
    <script>
        (function(d, s, id){
            var js, fjs = d.getElementsByTagName(s)[0];
            if(d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v3.0";
            fjs.parentNode.insertBefore(js, fjs);
        })(document, 'script', 'facebook-jssdk')
    </script>
    <div class ="fb-share-button" data-href='<%= "https://filmlegendary.herokuapp.com/#{@media}"%>' data-mobile-iframe = "true" data-layout="button"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= "#{controller_name}" %></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<%= yield(:social_media_meta)%>
		<%= csrf_meta_tags %>
		<%= tag :meta, name: :psj, action: action_name, controller: controller_name %>
  	<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
	<%= content_tag :body, data: {action: action_name, controller: controller_name} do %>
		<%= content_for?(:header) ? yield(:header) : render("layouts/header") %>
		<%= yield %>
		<%= yield :special_css%>
		<%= content_for?(:footer) ? yield(:footer) : render("layouts/footer") %>
  <%end%>
</html>