config/routes.rb
Rails.application.routes.draw do

  root 'films#index'
  post '/', to: 'films#index'

   #navigations for static pages
   get 'about', to: 'films#about'
   get 'contact', to: 'films#contactUs'
   get 'admin_index', to: 'admins#index'

   #search routes
   post '/search', to: 'latests#search'
   get '/search', to: 'latests#index'
 
  #navigation for paginated music page
  post '/musics_index', to: 'musics#index'
  get '/musics_index', to: 'musics#index'
  
  
  #navigation for paginated video page
  post '/videos_index', to: 'videos#index'
  get '/videos_index', to: 'videos#index'

  #navigation for paginated news page
  post '/news_index', to: 'news#index'
  get '/news_index', to: 'news#index'

 

  #routes for downloads
  post '/video_download', to: 'videos#download'
  post '/music_download', to: 'musics#download'

  #routes for authentication
  post '/auth', to: 'artists#auth'
  
  resources :musics, :videos, :news, :artists

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/video.rb
class Video < ApplicationRecord
    belongs_to :admin, optional: true
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

	def index
		respond_to do |format|
			format.json do 
				@query_offset = params[:offset].to_i
				@contents = Video.select(:id, :poster_path, :title).order(created_at: :desc).limit(6).offset(@query_offset)
				@query_offset += @contents.length
				@contents_json = Hash.new
				@contents_json["query"] = @query_offset
				@contents_json["contents"] = @contents.as_json
				render json: @contents_json
			end
			format.html do
				@query_offset=0;
				@contents = Video.select(:id, :poster_path, :title).order(created_at: :desc).limit(6)
				@query_offset += @contents.length
			end
		end
	end

	def new
		@video = Video.new
	end

	def create
		@videoService = VideoService.new(params)

		@videoService.create_locally

		@video = @videoService.store_video
		
		if @video
			flash[:customed_message] = @video.errors.full_messages
		end
		
		redirect_to admin_index_path
	end

	def show
		id = params[:id]
		@video = Video.find(id)
		@media = "videos/#{id}"
	end

	def download
		video_id = params[:video][:video_id]
		video = Video.find(video_id)

		if video.valid?
			video_rel_path = video.video_path
			
			video_name = File.basename video_rel_path

			video_file = gen_absolute_file_path video_rel_path

			send_file(video_file)
		end
	end

	private
		def permit_video
			params.require(:video).permit( :title, :producer, :description );
		end
end

app/helpers/videos_helper.rb
module VideosHelper
	def write_file file, path
			file_name = file.original_filename

			file_ext = File.extname file_name

			new_file = File.new(path, "wb")

			new_file.write(file.read)

			new_file.close
		end
end

app/views/videos/index.html.erb
<div class="template" hidden>
    <a class="link" href="">
        <div class="no-pad no-gutters media_content">
            <div class="col-6">
                <img class="poster" src="" alt="Mus14">
            </div>
            <div class="col-6 media_details">
                <span class="tag"></span>
            </div>
        </div>
    </a>
    <hr/>
</div>

<div class="title_holder">
    <span class="title">VIDEOS</span>
</div>
<div id= "content_holder">
    <% @contents.each do |video|%>
        <a href= <%= "/videos/#{video.id}" %> >
            <div class="no-pad no-gutters media_content">
                <div class="col-6">
                    <img class="poster" src=<%=video.poster_path%> alt="Mus14">
                </div>
                <div class="col-6 media_details column-display">
                    <span class="tag"><%=video.title%></span><br>
                </div>
            </div>
        </a>
        <hr/>       
    <% end %>    
</div>

<%= form_tag '/videos', name: 'per_page', remote: true do %>
    <%= hidden_field_tag 'offset', @query_offset %>
    <%= submit_tag 'load more...', disabled: false, id: 'load_content', class: 'more' %>
<% end %>

app/views/videos/show.html.erb
<div class="section no-pad no-gutters row">
    <div class="col-12">
        <span class="type rm_position">[ VIDEO ]</span>
        <span class="tag"><%= @video.title %></span>
    </div>
    <hr/>
    <div class="col-12">
    <video controls>
        <source src="<%= @video.video_path %>" type="video/mp4">
        <p>Your browser doesn't support HTML5 video. Here is
        a <a href="myVideo.mp4">link to the video</a> instead.</p>
    </video>
    </div>
    <div class="col-12 music-detail">
        <p><%= @video.description%></p>
        <span class="release lf-algn">released : <%= @video.released %></span><br/>
        <span class="producer lf-algn">produced : <%= @video.producer %></span>
    </div>
    <hr/>
    <div class="col-12 music-detail">
        <p class="specify">download <b><em><%= @video.title%></em></b> below</p>
        <%= form_for :video, url: video_download_path do |f| %>
            <%= f.hidden_field :video_id, value: @video.id %>
            <%= f.submit :download, class:"download_btn "%>
        <% end %>
    </div>
</div>
<%= render("layouts/social_media_share", locals:{media: @media})%>