config/routes.rb
Rails.application.routes.draw do

  root 'films#index'
  post '/', to: 'films#index'

   #navigations for static pages
   get 'about', to: 'films#about'
   get 'contact', to: 'films#contactUs'
   get 'admin_index', to: 'admins#index'

   #search routes
   post '/search', to: 'latests#search'
   get '/search', to: 'latests#index'
 
  #navigation for paginated music page
  post '/musics_index', to: 'musics#index'
  get '/musics_index', to: 'musics#index'
  
  
  #navigation for paginated video page
  post '/videos_index', to: 'videos#index'
  get '/videos_index', to: 'videos#index'

  #navigation for paginated news page
  post '/news_index', to: 'news#index'
  get '/news_index', to: 'news#index'

 

  #routes for downloads
  post '/video_download', to: 'videos#download'
  post '/music_download', to: 'musics#download'

  #routes for authentication
  post '/auth', to: 'artists#auth'
  
  resources :musics, :videos, :news, :artists

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/music.rb
class Music < ApplicationRecord
    belongs_to :artist, optional: true
    belongs_to :admin, optional: true
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
	def index
		respond_to do |format|
			format.json do 
				@query_offset = params[:offset].to_i
				@contents = Music.select(:media_id, :poster_path, :artist_name, :title).order(created_at: :desc).limit(1).offset(@query_offset)
				@query_offset += @contents.length
				@contents_json = Hash.new
				@contents_json["query"] = @query_offset
				@contents_json["contents"] = @contents.as_json
				render json: @contents_json
			end
			format.html do
				@query_offset=0;
				@contents = Music.select(:id, :poster_path, :artist_name, :title).order(created_at: :desc).limit(6)
				@query_offset += @contents.length
			end
		end
	end
	
	def new
		@music = Music.new
	end

	def create
		@musicService = MusicService.new(params)

		@musicService.create_locally()

		@music = @musicService.store_music()
		
		if @music
			flash[:customed_message] = @music.errors.full_messages
		end

		redirect_to admin_index_path
	end

	def show
		id = params[:id]
		@music = Music.find(id)
		@media = "musics/#{id}"
	end

	def download
		music_id = params[:music][:music_id]

		music =  Music.find(music_id)

		if music.valid?
			music_rel_path = music.music_path

			music_file = gen_absolute_file_path music_rel_path

			send_file(music_file)

			download_count = music.download_count + 1

			music.update(download_count: download_count)
		end
	end

	private
		def permit_music
			params.require(:music).permit(:producer, :music_path, :title, :poster_path, :album_title, :artist_name);
		end
end

app/helpers/musics_helper.rb
module MusicsHelper
    
end

app/views/musics/index.html.erb
<div class="template" hidden>
    <a class="link" href="">
        <div class="no-pad no-gutters media_content">
            <div class="col-6">
                <img class="poster" src="" alt="Mus14">
            </div>
            <div class="col-6 media_details">
                <span class="tag"></span>
                <p class="info">By : <span class="artist_name"></span></p>
            </div>
        </div>
    </a>
    <hr/>
</div>

<div class="title_holder">
    <span class="title">MUSICS</span>
</div>

<div id= "content_holder">
    <% @contents.each do |music|%>
        <a href= <%= "/musics/#{music.id}" %> >
            <div class="no-pad no-gutters media_content">
                <div class="col-6">
                    <img class="poster" src=<%=music.poster_path%> alt="Mus14">
                </div>
                <div class="col-6 media_details column-display">
                    <span class="tag"><%=music.title%></span><br>
                    <p class="info">By : <span class="artist_name"><%=music.artist_name%></span></p> 
                </div>
            </div>
        </a>
        <hr/>
    <% end %>
</div>

<%= form_tag '/musics', name: 'per_page', remote: true do %>
    <%= hidden_field_tag 'offset', @query_offset %>
    <%= submit_tag 'load more...', disabled: false, id: 'load_content', class: 'more' %>
<% end %>

app/views/musics/show.html.erb
<div class="section no-pad no-gutters row">
    <div class="col-12">
        <span class="type rm_position">[ MUSIC ]</span>
        <span class="tag"><%= @music.title %></span>
    </div>
    <hr/>
    <div class="col-12 disc-music">
        <img class="disc-music-poster" src=<%= @music.poster_path %> alt=<%= @music.title%>>
    </div>
    <div class="col-12 music-detail">
        <p><%= @music.description%></p>
        <span class="release lf-algn">released : <%= @music.released %></span><br/>
        <span class="producer lf-algn">produced : <%= @music.producer %></span>
    </div>
    <hr/>
    <div class="col-12 music-detail">
        <p class="specify">Listen and download <b><em><%= @music.title%></em></b> below</p>
        <audio controls>
            <source src="<%= @music.music_path %>" type="audio/mp3">
            <p>Your browser doesn't support HTML5 audio. Here is
                a <a href="@music.music_path">link to the audio</a> instead.
            </p>
        </audio>
        <%= form_for :music, url: music_download_path do |f| %>
            <%= f.hidden_field :music_id, value: @music.id %>
            <%= f.submit :download, class:"download_btn "%>
            <span class="sownload_count"><%= @music.download_count%></span>
        <% end %>
    </div>
</div>
<%= render("layouts/social_media_share", locals:{media: @media})%>